FROM mysql:latest
ENV MYSQL_DATABASE=lucas
ENV MYSQL_ROOT_PASSWORD=lucas
EXPOSE 3306
CMD ["mysqld"]

FROM influxdb:latest
ENV INFLUXDB_DB=lucas
ENV INFLUXDB_ADMIN_USER=admin
ENV INFLUXDB_ADMIN_PASSWORD=lucas
EXPOSE 8086
CMD ["influxd"]
